a = 10
b = 5
c = a+b
print(f"a + b = {c}")
c = a - b
print(f"a - b = {c}")
c = a * b
print(f"a * b = {c}")
c = a / b
print(f"a / b = {c}")
c = a // b
print(f"a // b = {c}")
c = a % b
print(f"a % b = {c}")
c = a ** b
print(f"a ** b = {c}")